export default [
  {
    title: 'ONLINE',
    img: '/Mountain-Bike.png',
    rating: '4.8',
    reviewCount: 33,
    country: 'USA',
    description: 'Join Group Mountain Biking',
    price: 130,
  },
  {
    title: 'SOLD OUT',
    img: '/image.png',
    rating: '5.0',
    reviewCount: 20,
    country: 'USA',
    description: 'Life lessons with Katie Zaferes',
    price: 135,
  },
  {
    title: 'ONLINE',
    img: '/wedding-photography.png',
    rating: '4.0',
    reviewCount: 35,
    country: 'USA',
    description: 'Learn wedding photography',
    price: 125,
  },
  {
    title: 'JOIN NOW',
    img: '/travel.jpg',
    rating: '4.9',
    reviewCount: 40,
    country: 'USA',
    description: 'Travel the World with us',
    price: 400,
  },
  {
    title: 'ONLINE',
    img: '/group-hiking.jpg',
    rating: '4.5',
    reviewCount: 25,
    country: 'USA',
    description: 'Join Group Hiking',
    price: 120,
  },
  {
    title: 'Favorite',
    img: '/Nature.jpg',
    rating: '4.5',
    reviewCount: 20,
    country: 'Austria',
    description: 'Explore the Nature with us',
    price: 300,
  },
];
